"""Generate AudioGuide Python option files from GUI project settings."""

from pathlib import Path

from .project import ProjectConfig


DEFAULT_SEARCH_TEXT = """SEARCH = [
	spass('closest', d('mfccs')),
]"""

DEFAULT_SUPERIMPOSE_TEXT = "SUPERIMPOSE = si(maxSegment=6)"


class OptionBuilderError(ValueError):
	"""Raised when a project config cannot produce a useful options file."""


class OptionBuilder:
	"""Build editable AudioGuide options-file text from a project config."""

	def build(self, config: ProjectConfig) -> str:
		"""Return Python option-file text for *config*."""
		return build_options_text(config)

	def build_file(self, config: ProjectConfig, destination_path: str | Path) -> Path:
		"""Write option-file text for *config* to *destination_path*."""
		return build_options_file(config, destination_path)


def build_options_file(config: ProjectConfig, destination_path: str | Path) -> Path:
	"""Write a Python AudioGuide options file and return its path."""
	destination = Path(destination_path)
	if destination.name == "":
		raise OptionBuilderError("destination_path must include a file name")
	destination.parent.mkdir(parents=True, exist_ok=True)
	destination.write_text(build_options_text(config), encoding="utf-8")
	return destination


def build_options_text(config: ProjectConfig) -> str:
	"""Return editable Python syntax compatible with AudioGuide options files."""
	_validate_config(config)
	output_dir = Path(config.output_dir)
	output_name = _clean_output_name(config.output_name)

	lines = [
		"# AudioGuide options file generated by AudioGuide GUI.",
		"# This is regular Python syntax and can be edited before rendering.",
		"",
		"############# INPUT FILES #############",
		f"TARGET = tsf({_py_string(config.target_path)})",
		"",
		"CORPUS = [",
	]
	lines.extend(f"\tcsf({_py_string(path)})," for path in config.corpus_paths)
	lines.extend(
		[
			"]",
			"",
			"############# MATCHING DEFAULTS #############",
			"# The GUI uses a conservative default search that advanced users may edit.",
			DEFAULT_SEARCH_TEXT,
			DEFAULT_SUPERIMPOSE_TEXT,
			"",
			"############# OUTPUT FILES #############",
			f"HTML_LOG_FILEPATH = {_py_string(output_dir / f'{output_name}-log.html')}",
			f"TARGET_SEGMENT_LABELS_FILEPATH = {_py_string(output_dir / f'{output_name}-targetlabels.txt')}",
			f"OUTPUT_LABEL_FILEPATH = {_py_string(output_dir / f'{output_name}-outputlabels.txt')}",
			f"DICT_OUTPUT_FILEPATH = {_optional_path(config.output_json, output_dir / f'{output_name}.json')}",
			"MAXMSP_OUTPUT_FILEPATH = None",
			"BACH_FILEPATH = None",
			"",
			"############# CSOUND RENDERING #############",
			f"CSOUND_CSD_FILEPATH = {_optional_path(config.render_csound, output_dir / f'{output_name}.csd')}",
			f"CSOUND_RENDER_FILEPATH = {_optional_path(config.render_csound, output_dir / f'{output_name}.aiff')}",
			"CSOUND_PLAY_RENDERED_FILE = False",
			"",
			"############# DAW OUTPUTS #############",
			f"RPP_FILEPATH = {_optional_path(config.output_reaper, output_dir / f'{output_name}.rpp')}",
			"RPP_AUTOLAUNCH = False",
			f"AAF_FILEPATH = {_optional_path(config.output_aaf, output_dir / f'{output_name}.aaf')}",
			"AAF_AUTOLAUNCH = False",
			"",
			"############# EXTRA RAW AUDIOGUIDE OPTIONS #############",
			"# Paste or edit advanced AudioGuide options below this line.",
			"# Values here run after the generated settings above, so they may override them.",
			config.extra_options_text,
			"",
		]
	)
	return "\n".join(lines)


def _validate_config(config: ProjectConfig) -> None:
	if not config.target_path:
		raise OptionBuilderError("target_path is required")
	if not config.corpus_paths:
		raise OptionBuilderError("at least one corpus path is required")
	if not config.output_dir:
		raise OptionBuilderError("output_dir is required")


def _clean_output_name(output_name: str) -> str:
	cleaned = output_name.strip()
	if not cleaned:
		raise OptionBuilderError("output_name is required")
	return Path(cleaned).stem


def _optional_path(enabled: bool, path: str | Path) -> str:
	if not enabled:
		return "None"
	return _py_string(path)


def _py_string(value: str | Path) -> str:
	return repr(str(value))


__all__ = [
	"OptionBuilder",
	"OptionBuilderError",
	"ProjectConfig",
	"build_options_file",
	"build_options_text",
]
